// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1P2hleul9TvkSBY-lRjmdlANSWj5nyOo',
    appId: '1:151149061094:web:d77cfd71fecc3fc83cac27',
    messagingSenderId: '151149061094',
    projectId: 'brugbart-21850',
    authDomain: 'brugbart-21850.firebaseapp.com',
    storageBucket: 'brugbart-21850.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLU4RfIzCiA7I9iQXkp8IOXUgI8kIlOHg',
    appId: '1:151149061094:android:6c300d10d41421763cac27',
    messagingSenderId: '151149061094',
    projectId: 'brugbart-21850',
    storageBucket: 'brugbart-21850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD08mBEPBuiRw305nmQTh-mcs61au3oyB8',
    appId: '1:151149061094:ios:e0d14ecde955d2443cac27',
    messagingSenderId: '151149061094',
    projectId: 'brugbart-21850',
    storageBucket: 'brugbart-21850.appspot.com',
    iosClientId:
        '151149061094-0bbj4qflmhe1dvv1b6rlnbf69u8sae19.apps.googleusercontent.com',
    iosBundleId: 'dk.brugbart.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD08mBEPBuiRw305nmQTh-mcs61au3oyB8',
    appId: '1:151149061094:ios:be87776877536f163cac27',
    messagingSenderId: '151149061094',
    projectId: 'brugbart-21850',
    storageBucket: 'brugbart-21850.appspot.com',
    iosClientId:
        '151149061094-u5ehehhi6sqfj5rr20hggcrljanqdepn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
